### ISSUE TITLE
REQUEST_CODE_CHOOSE constant unresolved in Kotlin translation

### ISSUE THREAD

**Issue by bettinasmid** [abhishekti7/UnicornFilePicker#2]
Hi,
I'm writing my program in Kotlin, so I had it translated by AndroidStudio, but the IDE cannot recognize this constant. Where do I find the declaration? The Kotlin adaptation of the function is below:

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode == **_REQUEST_CODE_CHOOSE_** && resultCode == RESULT_OK) {
            val files = data?.getStringArrayListExtra("filePaths")
            for (file in files!!) {
                Log.e("tag",file)
            }
        }
    }

Thanks a lot in advance!

**Comment by abhishekti7** [comment]
If you look at the function in the file `MainActivity.java`, the constant is actually named as **_REQ_UNICORN_FILE_** which is defined in the file _**Constants.java**_

Just replace the variable **REQUEST_CODE_CHOOSE** in your kotlin code with REQ_UNICORN_FILE ( don't forget to import the variable).

**Comment by bettinasmid** [comment]
Thanks a lot! 
Then the description in the Readme might be inaccurate?
![image](https://user-images.githubusercontent.com/61620783/108619908-547e2880-7428-11eb-8f28-031a8bbc2427.png)

**Comment by abhishekti7** [comment]
Actually, the request code in the readme demonstrates that you can put whatever integer constant you want in place. 
Glad I could be of help. I will be closing this issue now.
Thank you.
