### ISSUE TITLE
Longpress to select multiple files

### ISSUE THREAD

**Issue by mgood7123** [abhishekti7/UnicornFilePicker#4]
how would i go about implementing this feature? as a lot of file managers have this feature

**Comment by abhishekti7** [comment]
Hello @mgood7123 ,
Thank you for using UnicornFilePicker. 
Will you be willing to wait for a day or two for the new release as I had this feature in the roadmap for some time and was working on it.

**Comment by mgood7123** [comment]
> Hello @mgood7123 ,
> Thank you for using UnicornFilePicker. 
> Will you be willing to wait for a day or two for the new release as I had this feature in the roadmap for some time and was working on it.

Sure :)

**Comment by abhishekti7** [comment]
Hey @mgood7123,
there is already an option to select multiple files in the picker.
you just have to set that option in the builder like so

`.selectMultipleFiles(false)
`

There is no need for long-press. By enabling multiple select, you can select multiple files with just a click.

The long-press is reserved for a future update where the long-press would open a bottom sheet to display the file properties and/or some file operations.

**Comment by mgood7123** [comment]
> Hey @mgood7123,
> there is already an option to select multiple files in the picker.
> you just have to set that option in the builder like so
> 
> `.selectMultipleFiles(false)
> `
> 
> There is no need for long-press. By enabling multiple select, you can select multiple files with just a click.
> 
> The long-press is reserved for a future update where the long-press would open a bottom sheet to display the file properties and/or some file operations.
> 

Hmmm i think there should be an option that swaps this if desired
So long press selects multiple files
With an info button next to each file/folder displays that file/folder's information

So a user can easily select and multi select if desired without needing to re-open the view with different options

**Comment by mgood7123** [comment]
If you want, i can try to implement something like this after the update is released :)

**Comment by abhishekti7** [comment]
Sure, you can go ahead and start development on this if you like. It would be great for other developers who want the same feature

**Comment by mgood7123** [comment]
I will wait until the update is released as it will be easier for you to merge cus i dont know what code has been changed/rewritten
